<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_change_email</name>
   <tag></tag>
   <elementGuidId>52437185-8ee5-449f-80a2-e3a8a8e8c522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
