<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>946c17a2-cde6-4763-9447-c100c1e4f1ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/input[@id=&quot;account_password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
